### ISSUE TITLE
Title view collapses on the size of the first item.

### ISSUE THREAD

**Issue by mario-deluna** [qmathe/DropDownMenuKit#10]
Hello, I've got an issue with the DropDownTitleView, it seems to fix it's size to the first assigned text.

Even when constructing the view with a way to large frame I run into the same issue:

```swift
DropDownTitleView(frame: CGRect(x: 0, y: 0, width: 400, height: 40))
```

Images say more than words: 

<img width="200px;" src="https://cloud.githubusercontent.com/assets/956212/24742916/8381ad0c-1aac-11e7-9109-29adc9f845d5.png" />

<img width="200px;" src="https://cloud.githubusercontent.com/assets/956212/24742917/83b9043c-1aac-11e7-9480-9f5591c4541f.png" />

Do you have a recommendation how to solve this issue?

And a big thank you for the work you have put into this UI component.

**Comment by qmathe** [comment]
Hi,

Sorry for the very late reply, I was away for a while. I'm unable to reproduce your issue. May be you are updating the title view label directly with `DropDownTitleView.titleLabel.text` instead of using `DropDownTitleView.title`?

As shown in ViewController of DropDownMenuExample, the title view label must be updated like this:

```
	@IBAction func choose(_ sender: AnyObject) {
		titleView.title = "a new title"
	}
```

It's important to use the title property to get the title view internal layout recomputed. This layout computation is triggered by `DropDownTitleView.title` setter:

```
	open var title: String? {
		get {
			return titleLabel.text
		}
		set {
			titleLabel.text = newValue
	
			titleLabel.sizeToFit()
			layoutSubviews()
			sizeToFit()
		}
	}
```

If this doesn't help, could you show me the code that sets up the drop down menu and the one that updates the title view?

**Comment by pluckq** [comment]
Hello, same problem here, I'm setting title line in your example.
![simulator screen shot 29 2017 12 29 13](https://cloud.githubusercontent.com/assets/5019512/26540360/8ce4cd88-446a-11e7-826d-599102178482.png)
![simulator screen shot 29 2017 12 29 15](https://cloud.githubusercontent.com/assets/5019512/26540362/8d257f2c-446a-11e7-9d6e-f53eeb2952f1.png)
![simulator screen shot 29 2017 12 29 18](https://cloud.githubusercontent.com/assets/5019512/26540361/8d172ca6-446a-11e7-9a4a-77043416eb36.png)

**Comment by vadimvitvickiy** [comment]
You should change layout for label for something like this
```swift
titleLabel.frame.origin.x = frame.width/2 - titleLabel.frame.width/2
```
It's not about problem of TS, but about short titles

**Comment by qmathe** [comment]
Thanks for the suggestion, I'll commit a fix similar to this.

Did you manage to recreate the problem with the app example? 
Is it related to have left or right items in the navigation bar along the custom title view?

**Comment by vadimvitvickiy** [comment]
> Did you manage to recreate the problem with the app example?
Is it related to have left or right items in the navigation bar along the custom title view?

I had both left and right items in navigationBar
If u mean theme subject, I don't have problem like this, only short titles wrong layout which was left aligned

**Comment by qmathe** [comment]
@pluckq Thanks for your additional explanations.

I just committted a fix that should solve this problem together with issue #15 

Let me know if this fix works well.
