### ISSUE TITLE
Use in Objective-C code?

### ISSUE THREAD

**Issue by gerchicov-bp** [qmathe/DropDownMenuKit#11]
I have a project which combines both swift and objective-c code. How to import it into objective-C code correctly - it can't find the path?

**Comment by qmathe** [comment]
Hi,

Sorry for the late reply, I was away for a month or so. 

Did you try `#import <DropDownMenuKit/DropDownMenu-Swift.h>` and similar imports for the other classes from DropDownMenuKit?

I haven't tried it yet though. I'll take a look at it and see if any tweaks is needed on my side.

**Comment by gerchicov-bp** [comment]
finally I imported this library as sources and edited it instead of cocoapods. The problem is objective C doesn't fully support swift code. For example some public methods should be marked with `@objc`, some structures/classes are not supported (for example enums with methods)

**Comment by qmathe** [comment]
As you outline it, to make it compatible with ObjC would require some substantial changes and I'm not sure it's worth investment.

I might give it a try at some point, but it's not a high priority for me currently.
