### ISSUE TITLE
Inheritance is forbidden

### ISSUE THREAD

**Issue by gerchicov-bp** [qmathe/DropDownMenuKit#12]
```
required public init?(coder aDecoder: NSCoder) {
	    fatalError("init(coder:) has not been implemented")
	}
```
wtf? I want to create a cell with xib file but I can't because of this useless code

**Comment by qmathe** [comment]
Hi,

I didn't implement coding support because I had no need for it and nobody requested it until now. If you have implemented it, you can send me a pull request and I'll merge it.

Otherwise I'll add it to my to-do list and let you know once it's supported.

**Comment by gerchicov-bp** [comment]
The problem is your library involves custom cells. But by using of this code you forbid them

**Comment by qmathe** [comment]
Would be nice to have I agree. I'll try to implement it soon.

**Comment by qmathe** [comment]
I implemented basic decoding for `DropDownMenu` and `DropDownMenuCell`, see 36d5956fd292f5f897ced6dede961885e7cf785d. This will be included in the next release.
