### ISSUE TITLE
How can I change the color of drop image or up image?

### ISSUE THREAD

**Issue by littlemozart** [qmathe/DropDownMenuKit#13]
Hi, I have tried to use "titleView.menuDownImageView.tintColor = UIColor.white" but it didn't work. The color was still black. Any other ideas to change it?

**Comment by qmathe** [comment]
Hi,

Sorry for the late reply, I was away for a month. 

I committed a change to support what you want to do.

If you want to work around this issue for the current release, just change the rendering of up/down images like this:

```
titleView.menuDownImageView.image = titleView.menuDownImageView.image.withRenderingMode(.alwaysTemplate)
titleView.menuDownImageView.tintColor = UIColor.white
```

**Comment by littlemozart** [comment]
@qmathe Thank you for your reply.
