### ISSUE TITLE
Centering text + image

### ISSUE THREAD

**Issue by rico237** [qmathe/DropDownMenuKit#16]
Depending on text size the collapse image and text are not centered ... 

![simulator screen shot 25 juil 2017 a 01 25 09](https://user-images.githubusercontent.com/4282169/28549065-26aa4238-70d8-11e7-8cbb-b93b5776691b.png)
![simulator screen shot 25 juil 2017 a 01 25 07](https://user-images.githubusercontent.com/4282169/28549066-26addbaa-70d8-11e7-8a8d-c6e66e5edd49.png)
![simulator screen shot 25 juil 2017 a 01 25 04](https://user-images.githubusercontent.com/4282169/28549067-26af2168-70d8-11e7-9473-21c434c39acf.png)

**Comment by qmathe** [comment]
Hi, 

Thanks for the bug report, I'm going to take a look at it.

**Comment by ashleyhenderson** [comment]
I'm having a similar error, where if the initial title text is longer than the next chosen option - the new title appears off-centre as pictured
![image1 1](https://user-images.githubusercontent.com/26363840/28978311-69ed17c4-793d-11e7-9ce7-54ab26fc4624.PNG)
![image1](https://user-images.githubusercontent.com/26363840/28978318-6da29984-793d-11e7-9c34-b5ad279a8e34.PNG)

**Comment by ashleyhenderson** [comment]
Do you happen to have an ETA on a fix for this?

EDIT: Apologies! I just checked your code here and our version doesn't incorporate your fix 2 months ago for this issue. Can confirm your most recent GitHub version fixes the bug. It's quite strange as we installed 2 days ago via cocoapods but seem to have picked up the wrong version!

**Comment by qmathe** [comment]
Yes, this issue has already been fixed in master with cbd130a.

I just committed an extra fix to ensure the title is correctly centered, even when you don't call `DropDownMenu.selectMenuCell()` while creating the menu.

I'm going to make another CocoaPods release, the current one is quite outdated now.

**Comment by ashleyhenderson** [comment]
Fantastic! The updated cocoapods release would be much appreciated 🙂

**Comment by qmathe** [comment]
Just pushed the new 0.8.3 release to CocoaPods!
