### ISSUE TITLE
Drop Down Menu does not work in a popup 

### ISSUE THREAD

**Issue by ha-hamed** [qmathe/DropDownMenuKit#17]
I have a issue when using the drop down menu in pop up and choosing a cell: I get the following error: 

<img width="1657" alt="screen shot 2017-08-24 at 4 10 31 pm" src="https://user-images.githubusercontent.com/5396417/29670411-d947c28c-88e6-11e7-82a1-2c8f00d7db3e.png">

**Could you please provide a solution for it? Thank you in advance**

**Comment by qmathe** [comment]
Thanks for reporting the issue, I'm going to take a look at it.

**Comment by ha-hamed** [comment]
@qmathe Thank you, it will be deeply appreciated.

**Comment by qmathe** [comment]
Did you assign the view of the popup controller to `DropDownMenu.container`before presenting it ?

If you did this and `DropDownMenu.container` was reverted to nil while getting presented, I'll need some code to better understand how you are setting up the menu, in order to reproduce the issue.

If you can provide a test project or modify DropDownMenuExample to reproduce the issue, that's even better.

**Comment by ha-hamed** [comment]
@qmathe I just adjusted my code to the usage of the release 0.8.4, however, still I am having trouble with creating a dropdown in the pop up controller view. Could you please put a sample/example code? I have displayed` DropDownMenu.container` and assigned it to the popup controller and still the drop down menu is not displaying/functioning in a pop up view controller. Any help to would be appreciated greatly.

**Comment by qmathe** [comment]
@hakuj I have some time to investigate this issue again. Any update on your side. Did you find a solution?

By pop up controller, do you mean a [popover controller](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller)?

I'll try to create a small example based on the screenshot you gave me. If you have a test project that shows what you were trying to achieve that would still be helpful.

**Comment by qmathe** [comment]
If this problem still happens, please let me know. I'm closing it for now.
