### ISSUE TITLE
DropDown doesn't work on iOS 11 device

### ISSUE THREAD

**Issue by sway0422** [qmathe/DropDownMenuKit#19]
The dropdown menu is not clickable and looks much smaller on iOS 11 devices.

**Comment by qmathe** [comment]
ok, thanks for reporting the issue. I'll take a look at it.

**Comment by rico237** [comment]
Same issue here :)

**Comment by siyavash4812** [comment]
any updates for IOS11 and Xcode 9?

**Comment by ashleyhenderson** [comment]
Do you have an ETA on this fix?

**Comment by qmathe** [comment]
Took me a bit longer than I expected to fix, but iOS 9 to 11 should be properly supported now.

If sizing issues remain on iOS 11, let me know about them.

Thanks for the bug report.
