### ISSUE TITLE
Menu and container not released

### ISSUE THREAD

**Issue by IngwarSkjold** [qmathe/DropDownMenuKit#21]
Variable 'container' in DropDownMenu.swift (line 23) is strong reference, therefore when container is removed from view hierarhy it maintains referenced by DropDownMenu and can not be destroyed.
Solution: make container weak reference and perform necessary checks in methods show, hide and  visibleContentOffset.didSet

**Comment by qmathe** [comment]
Thanks for catching this. Should be fixed now.

**Comment by IngwarSkjold** [comment]
Thanks for resolving.
