### ISSUE TITLE
Broken cocoapods

### ISSUE THREAD

**Issue by gerchicov-bp** [qmathe/DropDownMenuKit#25]
You specified "swift 4.2" in podspec but in the same time by default the `pod install` command ignores `master` and downloads branch for "4.1"

**Comment by qmathe** [comment]
Hi,

Which version are you trying to install 0.8.5 or master? Did you declare DropDownMenuKit in your Podfile as shown below or in another way?

```
target 'Test' do
  pod 'DropDownMenuKit', :git => 'https://github.com/qmathe/DropDownMenuKit.git'
end
```

To make things clearer, I just removed the reference to _0.8.5_ tag in the podspec of **master**, see 86a9eefadf297d2014bbe7dfb3e11699dabc68ca. I doubt this changes anything though. Installing master was working fine in my tests before this change. 

The source entry in the podspec in master should also be ignored when referring to a custom source like `:git => 'https://github.com/qmathe/DropDownMenuKit.git'` in a Podfile.
