### ISSUE TITLE
UIViewAnimationOptions' has been renamed to 'UIView.AnimationOptions'

### ISSUE THREAD

**Issue by Rjmaurya13** [qmathe/DropDownMenuKit#27]
UIViewAnimationOptions' has been renamed to 'UIView.AnimationOptions'

**Comment by qmathe** [comment]
The renaming has already been done in **master** when migrating to **Swift 4.2**, see e229b807f7d084d2fd644809a769de279be3b46b. I'll make a new release with this change soon. Thanks!

**Comment by qmathe** [comment]
I just made a new release 0.8.6 that includes this change.
