### ISSUE TITLE
Error retrieving icon from bundle

### ISSUE THREAD

**Issue by PasqualePuzio** [qmathe/DropDownMenuKit#31]
Hi,

in some cases this pod can raise an error (and cause a crash) when retrieving an icon from the xcassets file.

This happens when you subclass DropDownTitleView, therefore the pod can't retrieve the bundle in which the icon is supposed to be and finally crashes trying to unwrap a nil value.

The fix is very easy: https://github.com/DigitalGoal-Ltd/DropDownMenuKit/commit/e98532c875641325fae56fa5c48ade2cd8cc51a8

**Comment by qmathe** [comment]
Hi,

I'll apply your fix later this week-end. Thanks for the report!
