### ISSUE TITLE
Pod Build fails with current version of Swift

### ISSUE THREAD

**Issue by james-ff** [qmathe/DropDownMenuKit#7]
Integrated the framework via Cocoapods. When I build my project this framework lists 20 or so errors. Would love to use this library, could you guys take a look and build it with the latest Xcode and Swift, and update the pod spec to use the latest version? Thanks. @qmathe @grifas

**Comment by qmathe** [comment]
Sorry for the late reply. I'll take a look at updating the project for the latest Swift in the next days.

**Comment by nicholas-jomo** [comment]
@qmathe it seems the 0.8.1 on Pod does not support Swift 3, same errors for me

@james-ff you may use this for now

`pod 'DropDownMenuKit', git: 'https://github.com/qmathe/DropDownMenuKit'`

**Comment by qmathe** [comment]
I just published a new version 0.8.2 with Swift 3 support. I also updated the corresponding pod. Let me know how it goes.
