### ISSUE TITLE
Table view not filled

### ISSUE THREAD

**Issue by grifas** [qmathe/DropDownMenuKit#9]
Hi, 
I fetch my data asynchronously and I fill the menuCells once I have it. My issue is the table view is not filled or may be is not displayed.

Have you a solution ?

**Comment by qmathe** [comment]
After updating your cells in response to your asynchronous call, did you try calling DropDownMenu.menuView.reloadData() or similar reload methods?

**Comment by grifas** [comment]
I'm using Firebase and in the viewDidLoad I'm fetching data asynchronously and yes after I have it I tried to reload the tableView. The numberOfRow returns the right number but it never passes in cellForRow. I think the height of content is 0.

**Comment by qmathe** [comment]
I committed a fix for your issue. Let me know if it is working for you now.

**Comment by grifas** [comment]
It seems to be fixed :)

**Comment by qmathe** [comment]
Thanks for reporting the bug :)
